# Generated by Django 4.0.3 on 2022-03-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas_app', '0003_receita_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='foto_receita',
            field=models.ImageField(blank=True, upload_to='fotos/%d/%m/%Y/'),
        ),
    ]
